// Explicit retirement of the initial HTML migration, never a crawl result or live network test.
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const {publish,readPublished,normalizeJobs,coverageFor}=require('../crawler/publish');
const A={key:'a',company:'Alpha',ats:'moka',orgId:'fixture',siteId:123,site:'social'},B={...A,key:'b',company:'Beta'};
const time='2026-01-01T00:00:00.000Z';
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ande-initial-legacy-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const dataFile=path.join(dir,'jobs.js'),outDir=path.join(dir,'out');fs.mkdirSync(outDir);fs.writeFileSync(path.join(outDir,'b_status.json'),'MALFORMED READY CANDIDATE MUST NEVER BE READ');
 const old={...normalizeJobs([{id:'unused',title:'旧岗位'}],B)[0],id:'legacy-b-135',date:'2099-01-01',dateKind:null};
 const fresh=normalizeJobs([{id:'1',title:'官方空正文',duty:'',requirements:'',employment:null,talentPlan:null},{id:'legacy-b-136',title:'官方ID可含legacy字样',description:'完整正文'}],A);
 const data={version:1,legacy:true,notices:['仍含历史个人筛选基线'],companies:[{name:'Alpha',initial:'A',aliases:'Alpha'},{name:'Beta',initial:'B',aliases:['Beta']}],sources:[{key:'a',company:'Alpha',status:'failed',lastSuccess:time,lastAttempt:'2026-01-02T00:00:00.000Z',coverage:coverageFor(A),message:'曾验证，最近失败'},{key:'b',company:'Beta',status:'legacy',lastSuccess:null,lastAttempt:null,coverage:'历史个人筛选范围，待全量化',message:'初版迁移'}],jobs:[old,...fresh]};fs.writeFileSync(dataFile,'globalThis.ANDE_DATA = '+JSON.stringify(data)+';\n');return {data,dataFile,outDir,sites:[A,B]};}
test('explicit retirement removes only migration IDs; unknown facts/blank JD/failed but previously verified source survive',t=>{const f=fixture(t),out=fs.readFileSync(path.join(f.outDir,'b_status.json')),source=f.data.sources[0],jobs=f.data.jobs.slice(1),result=publish({...f,discardLegacy:true});assert.equal(result.code,0);assert.equal(result.written,true);assert.deepEqual(result.updated,[]);assert.equal(result.discardedLegacy,1);assert.deepEqual(result.data.jobs,jobs);assert.deepEqual(result.data.sources[0],source);assert.equal(result.data.legacy,false);assert.deepEqual(result.data.companies,f.data.companies);assert.equal(result.data.sources[1].status,'unavailable');assert.equal(result.data.sources[1].coverage,null);assert.equal(result.data.sources[1].lastSuccess,null);assert.equal(result.data.sources[1].lastAttempt,null);assert.ok(result.data.notices.some(n=>n.includes('初版HTML遗留岗位不再保留')));assert.ok(!result.data.notices.some(n=>n.includes('仍含历史个人筛选基线')));assert.deepEqual(fs.readFileSync(path.join(f.outDir,'b_status.json')),out);
 const before=fs.readFileSync(f.dataFile),mtime=fs.statSync(f.dataFile,{bigint:true}).mtimeNs;assert.equal(publish({...f,discardLegacy:true}).written,false);assert.deepEqual(fs.readFileSync(f.dataFile),before);assert.equal(fs.statSync(f.dataFile,{bigint:true}).mtimeNs,mtime);assert.equal(publish({...f,keys:['a']}).written,false);assert.deepEqual(fs.readFileSync(f.dataFile),before);});
test('maintenance cannot mix source publication or silently accept approximate/provenance-mismatched migration identity',t=>{const f=fixture(t),before=fs.readFileSync(f.dataFile);for(const options of [{discardLegacy:true,keys:['a']},{discardLegacy:true,failedKeys:['a']},{discardLegacy:'true'}])assert.throws(()=>publish({...f,...options}),/explicit and separate/);assert.deepEqual(fs.readFileSync(f.dataFile),before);
 for(const id of ['legacy-b-135extra','legacy-a-135','legacy-b--135']){const data={...f.data,jobs:[{...f.data.jobs[0],id},...f.data.jobs.slice(1)]};fs.writeFileSync(f.dataFile,'globalThis.ANDE_DATA = '+JSON.stringify(data)+';\n');const bytes=fs.readFileSync(f.dataFile);assert.throws(()=>publish({...f,discardLegacy:true}),/identity\/provenance mismatch/);assert.deepEqual(fs.readFileSync(f.dataFile),bytes);}
 const data=JSON.parse(JSON.stringify(f.data));data.sources[1].lastSuccess=time;fs.writeFileSync(f.dataFile,'globalThis.ANDE_DATA = '+JSON.stringify(data)+';\n');assert.throws(()=>publish({...f,discardLegacy:true}),/identity\/provenance mismatch/);});
test('first-attempt failure status does not change initial-ID retirement, and empty legacy sources are not verified zero',t=>{const f=fixture(t);f.data.sources[1].status='failed';f.data.sources[1].lastAttempt=time;f.data.sources.push({key:'empty',company:'Beta',status:'legacy',lastSuccess:null,lastAttempt:null,coverage:null,message:'未核'});fs.writeFileSync(f.dataFile,'globalThis.ANDE_DATA = '+JSON.stringify(f.data)+';\n');const r=publish({...f,discardLegacy:true});assert.equal(r.discardedLegacy,1);assert.deepEqual(r.data.sources[1],{...f.data.sources[1],status:'unavailable',coverage:null,message:'初版HTML遗留岗位已按用户授权退出；尚未取得已验证的新快照，不表示官网无岗位或已下架'});assert.equal(r.data.sources[1].lastAttempt,time);assert.equal(r.data.sources[2].status,'unavailable');assert.equal(r.data.sources[2].lastSuccess,null);});
test('already-unavailable empty initial sources retire metadata by provenance, never by absence of jobs',t=>{const f=fixture(t);f.data.sources.push({key:'empty',company:'Beta',status:'unavailable',lastSuccess:null,lastAttempt:null,coverage:'历史个人筛选范围，待全量化',message:'初版迁移'},{key:'new_empty',company:'Beta',status:'unavailable',lastSuccess:null,lastAttempt:time,coverage:'new-scope',message:'新协议暂未成功'});fs.writeFileSync(f.dataFile,'globalThis.ANDE_DATA = '+JSON.stringify(f.data)+';\n');const r=publish({...f,discardLegacy:true});assert.equal(r.data.sources[2].coverage,null);assert.match(r.data.sources[2].message,/初版HTML遗留岗位已按用户授权退出/);assert.equal(r.data.sources[2].lastSuccess,null);assert.deepEqual(r.data.sources[3],f.data.sources[3]);const m=fs.statSync(f.dataFile,{bigint:true}).mtimeNs;assert.equal(publish({...f,discardLegacy:true}).written,false);assert.equal(fs.statSync(f.dataFile,{bigint:true}).mtimeNs,m);});
test('no initial data is a no-op, normal publication still needs a verified snapshot',t=>{const f=fixture(t);fs.unlinkSync(f.dataFile);assert.equal(publish({...f,discardLegacy:true}).written,false);assert.equal(fs.existsSync(f.dataFile),false);assert.equal(publish({...f,keys:['a']}).written,false);assert.equal(fs.existsSync(f.dataFile),false);});
test('atomic-write failure leaves original data intact and no temp file',t=>{const f=fixture(t),before=fs.readFileSync(f.dataFile),original=fs.renameSync;fs.renameSync=(from,to)=>{if(to===f.dataFile)throw Error('fixture rename failure');return original(from,to);};try{assert.throws(()=>publish({...f,discardLegacy:true}),/fixture rename failure/);}finally{fs.renameSync=original;}assert.deepEqual(fs.readFileSync(f.dataFile),before);assert.ok(!fs.readdirSync(path.dirname(f.dataFile)).some(n=>n.endsWith('.tmp')));});
test('CLI flag cannot accidentally trigger all-source publication or mix with keys',()=>{const result=spawnSync(process.execPath,[path.join(__dirname,'../crawler/publish.js'),'--discard-legacy','alibaba_social'],{encoding:'utf8'});assert.equal(result.status,1);assert.match(result.stderr,/Unknown source key/);});
