const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const m=require('../crawler/lib/custom/meituan_campus_portal'),{normalizeJobs,publish,readPublished,loadSites}=require('../crawler/publish'),{runCrawl,adapterCommand}=require('../crawler/crawl');
const clone=structuredClone,LIST=m.PROFILE.api,DETAIL='https://zhaopin.meituan.com/api/official/job/getJobDetail';
function job(type){return{jobUnionId:type,name:'完整岗位'+type,projectId:null,projectName:null,jobType:type,jobSpecialCode:'8',jobSource:'2',jobStatus:'000',jobFamily:'技术',jobFamilyGroup:'专业',cityList:[],workYear:null,department:[],desc:null,departmentIntro:'部门真实全文',jobDuty:'职责完整TEXT & <标记>',jobRequirement:'要求原文',precedence:null,highLight:null,otherInfo:null,firstPostTime:null,refreshTime:1786961006000,tag:[0],expiredTime:null,socialRecommendJob:null};}
function seq(){const rows=[job('1'),job('2')],out=[];const add=(codes,n,ids,total)=>out.push({url:LIST,body:{...clone(m.PROFILE.body),jobType:codes.map(code=>({code,subCode:[]})),page:{pageNo:n,pageSize:1000}},response:{status:1,message:'成功',data:{list:ids,page:{pageNo:n,pageSize:1000,totalCount:total,totalPage:Math.ceil(total/1000)},traceId:null}}});
 add(['1','2'],1,clone(rows),2);for(let r=0;r<2;r++)for(const row of rows){add([row.jobType],1,[clone(row)],1);add([row.jobType],2,null,1);out.push({url:DETAIL,body:{jobUnionId:row.jobUnionId,jobShareType:'1'},response:{status:1,message:'成功',data:clone(row)}});}add(['1','2'],1,clone(rows),2);return out;}
function options(queue){return{sleep:async()=>{},fetchImpl:async(url,o)=>{const row=queue.shift();a.equal(url,row.url);a.deepEqual(JSON.parse(o.body),row.body);a.equal(o.redirect,'manual');return{status:200,json:async()=>clone(row.response)};}};}
async function raw(){return m.fetchAll(m.PROFILE,options(seq()));}
test('fixed campus OR scope has no project/exclusion filter and cannot downgrade into legacy/social',()=>{a.deepEqual(loadSites().find(s=>s.key==='meituan'),m.PROFILE);a.equal(adapterCommand(m.PROFILE,'out').timeout,900000);for(const change of [p=>p.body.jobType.pop(),p=>p.exclude='北斗',p=>p.body.specialCode=['8'],p=>delete p.adapter,p=>p.ats='feishu',p=>p.url='javascript:alert(1)']){const p=clone(m.PROFILE);change(p);a.equal(m.verifiedSource(p),false);a.equal(adapterCommand(p,'out'),null);a.throws(()=>normalizeJobs([job('1')],p),/verified|scope|identity/);}});
test('all partitions, typed EOF and necessary details twice produce exact union, not dedup/default sample success',async()=>{const r=await raw();a.equal(r.total,2);a.equal(m.validateEvidence(r.verification,r.jobs,m.PROFILE),true);a.deepEqual(r.jobs.map(j=>j.jobType),['1','2']);const p=normalizeJobs(r.jobs,m.PROFILE);a.equal(Object.keys(p[0]).length,17);a.equal(p[0].duty,'职责完整TEXT & <标记>');a.equal(p[0].date,null);a.equal(p[0].employment,null);a.deepEqual(p[1].channels,[]);a.equal(p[1].employment,'internship');});
test('partition leakage/duplicates, total/default membership and all raw facts drift reject whole campus source',async()=>{const r=await raw();const changes=[e=>e.scans.pop(),e=>e.scans[0].partitions.pop(),e=>e.scans[0].partitions[0].pages.pop(),e=>e.scans[0].partitions[0].details.pop(),e=>e.scans[0].partitions[0].pages[0].response.data.list[0].jobType='2',e=>e.scans[0].partitions[1].pages[0].response.data.list[0].jobUnionId='1',e=>e.bounds[0].response.data.page.totalCount=3,e=>e.bounds[0].response.data.list[0].jobUnionId='99',e=>e.scans[1].partitions[0].details[0].response.data.departmentIntro+='漂移',e=>e.scans[1].partitions[0].details[0].response.data.otherInfo='暂无',e=>e.scans[0].partitions[0].pages[1].response.data.list=[]];for(const change of changes){const e=clone(r.verification);change(e);a.throws(()=>m.validateEvidence(e,r.jobs,m.PROFILE),/Meituan/);}});
test('scope/layout unknown content and types are not silently stripped or inferred',()=>{for(const mutate of [j=>j.tag=[2],j=>j.jobType='3',j=>j.projectName='未知正文',j=>j.otherInfo=' ',j=>j.extraJD='新增正文',j=>j.jobDuty={}]){const j=job('1');mutate(j);a.throws(()=>m.validateJobs([j],m.PROFILE),/Meituan/);}});
test('official campus renderer branches labels/city footer and does not count attributes as real JD',async()=>{const j=job('1');j.desc='not displayed in formal branch';a.equal(m.normalizeRecord(j,m.PROFILE).description,'岗位职责\n'+j.jobDuty+'\n\n任职要求\n'+j.jobRequirement+'\n\n工作城市\n');j.jobDuty=null;j.jobRequirement=null;j.cityList=[{code:null,name:'北京市',children:null,sort:null,subCode:null,mapping:null,outerCode:null,bgNode:false}];a.equal(m.normalizeRecord(j,m.PROFILE).jdComplete,false);j.jobSpecialCode='6';a.ok(m.normalizeRecord(j,m.PROFILE).description.includes('岗位描述\nnot displayed in formal branch'));const q=seq();for(const x of q)if(x.url===DETAIL){x.response.data.projectId='115';x.response.data.projectName='2026年（2027届）秋季校招';x.response.data.department=[{code:'BG050',name:'真实部门',children:null,sort:null,subCode:null,mapping:null,outerCode:null,bgNode:false}];}a.equal((await m.fetchAll(m.PROFILE,options(q))).total,2);});
test('real campus 4697281262 null city hides footer, keeps raw and never fills missing body',async()=>{const q=seq();for(const x of q){const rows=x.url===DETAIL?[x.response.data]:x.response.data.list??[];for(const row of rows)if(row.jobType==='1')row.cityList=null;}const r=await m.fetchAll(m.PROFILE,options(q));a.equal(r.jobs[0].cityList,null);const j=m.normalizeRecord(r.jobs[0],m.PROFILE);a.deepEqual(j.city,[]);a.ok(!j.description.includes('工作城市'));const e=clone(r.verification);e.scans[1].partitions[0].details[0].response.data.cityList=[];a.throws(()=>m.validateEvidence(e,r.jobs,m.PROFILE),/null campus city/);});
test('campus uses the sole crawl/snapshot/publisher chain; corrupt evidence cannot publish and failure preserves last success',async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'ande-campus-test-')),out=path.join(d,'out'),data=path.join(d,'jobs.js'),r=await raw();const envelope={key:'meituan',api:LIST,mode:'custom',...r};try{const success=await runCrawl(m.PROFILE,{outDir:out,now:()=> '2026-10-07T00:00:00.000Z',runner:(_c,args)=>{fs.writeFileSync(args.at(-1),JSON.stringify(envelope));return{status:0};},log:()=>{}});a.equal(success.code,0);const published=publish({outDir:out,dataFile:data,sites:[m.PROFILE],keys:['meituan']});a.equal(published.code,0);a.equal(readPublished(data).jobs.length,2);const broken=clone(envelope);broken.verification.scans[1].partitions.pop();const fail=await runCrawl(m.PROFILE,{outDir:out,now:()=> '2026-10-07T01:00:00.000Z',runner:(_c,args)=>{fs.writeFileSync(args.at(-1),JSON.stringify(broken));return{status:0};},log:()=>{}});a.equal(fail.code,1);a.equal(JSON.parse(fs.readFileSync(path.join(out,'meituan_status.json'))).lastSuccess,'2026-10-07T00:00:00.000Z');publish({outDir:out,dataFile:data,sites:[m.PROFILE],keys:['meituan'],failedKeys:['meituan']});a.deepEqual(readPublished(data).jobs,published.data.jobs);a.equal(readPublished(data).sources[0].lastSuccess,'2026-10-07T00:00:00.000Z');}finally{fs.rmSync(d,{recursive:true,force:true});}});
