'use strict';
// Offline only: complete list JD mode must not mechanically refetch every detail.
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const moka=require('../crawler/lib/moka'),{normalizeJobs,coverageFor}=require('../crawler/publish');
const site={key:'kimi',company:'月之暗面',ats:'moka',orgId:'moonshot',siteId:148507,site:'campus',listJD:true,adapter:'moka-portal-v1',aesIv:'de7c21ed8d6f50fe',url:'https://app.mokahr.com/campus-recruitment/moonshot/148507'};
const job=(id='a',extra={})=>({id,orgId:'moonshot',title:'其他职业',jobDescription:'<p>工作职责</p><p>运营 Agent</p><p>任职要求</p><p>熟悉 Agent</p>',commitment:'实习',zhineng:{name:'市场'},locations:[],publishedAt:'2026-09-23T14:04:58',status:'open',...extra});
function fixture(pages){const requests=[];return {requests,fetchImpl:async(url,opt)=>{a.ok(url.endsWith('/jobs/v2'),'No mechanical detail requests');requests.push({url,body:JSON.parse(opt.body),headers:opt.headers});const p=pages[requests.length-1];a.ok(p,'Unexpected extra request');return {status:p.status??200,text:async()=>JSON.stringify({code:0,success:true,data:{jobStats:{orgId:'moonshot',total:p.total??p.jobs.length},jobs:p.jobs}})};}};}
const run=(pages,extra={})=>{const f=fixture(pages);return {f,promise:moka.fetchAll(site,{...f,sleep:async()=>{},...extra})};};
test('complete list JD uses two full scans, preserves raw HTML/nature, normalizes once without extra detail calls',async()=>{const j=job(),{f,promise}=run([{jobs:[j]},{jobs:[j]}]);const r=await promise;a.equal(f.requests.length,2);a.equal(r.jobs[0].listJDVerified,true);a.equal(r.jobs[0].jobDescription,j.jobDescription);const n=normalizeJobs(r.jobs,site)[0];a.equal(n.jdComplete,true);a.equal(n.employment,'internship');a.deepEqual(n.channels,['campus']);a.equal(n.date,'2026-09-23');a.equal(n.dateKind,'published');a.ok(n.duty.includes('运营 Agent'));a.ok(n.requirements.includes('熟悉 Agent'));a.equal(n.description,'');});
test('raw fields and identity must remain stable through the second scan, not only count or ID set',async()=>{for(const fields of [{jobDescription:'changed'},{title:'changed'},{commitment:'全职'},{zhineng:{name:'设计'}},{locations:[{country:'美国'}]},{status:'pause'},{publishedAt:'2026-01-01'}])await a.rejects(run([{jobs:[job()]},{jobs:[job('a',fields)]}]).promise);});
test('invalid full JD and bad identities reject the whole source, never silently skip malformed records',async()=>{for(const j of [job('a',{jobDescription:[]}),job('a',{jobDescription:{text:'x'}}),job('',{}),job('a',{orgId:'foreign'})])await a.rejects(run([{jobs:[j]},{jobs:[j]}]).promise);await a.rejects(run([{jobs:[job(),job()]},{jobs:[job(),job()]}]).promise);});
test('two explicit empty scans are required and official empty or symbol JD is retained honestly',async()=>{a.equal((await run([{jobs:[]},{jobs:[]}]).promise).total,0);await a.rejects(run([{jobs:[]},{jobs:[job()]}]).promise);for(const html of ['',null,'<p>。</p>']){const r=await run([{jobs:[job('a',{jobDescription:html,publishedAt:null})]},{jobs:[job('a',{jobDescription:html,publishedAt:null})]}]).promise;const n=normalizeJobs(r.jobs,site)[0];a.equal(n.jdComplete,false);a.equal(n.date,null);a.equal(n.dateKind,null);}});
test('omitted JD is an observed official optional field, retained as an honest blank, not a crawl failure',async()=>{const j=job();delete j.jobDescription;const r=await run([{jobs:[j]},{jobs:[j]}]).promise,n=normalizeJobs(r.jobs,site)[0];a.equal(r.total,1);a.equal(n.jdComplete,false);a.equal(n.description,'');});
test('new list-mode markers and published-date field are checked before normalization',()=>{for(const fields of [{listJDVerified:undefined},{listJDVerified:false},{jobDescription:undefined},{publishedAt:7}])a.throws(()=>normalizeJobs([{...job(),listJDVerified:true,...fields}],site));a.notEqual(coverageFor(site),coverageFor({...site,listJD:false}));});
test('missing publication does not fall back to opened/created clocks or infer internship from title',async()=>{const j=job('a',{title:'运营实习生',commitment:'全职',publishedAt:null,createdAt:'2025-01-01',openedAt:'2025-02-01'}),r=await run([{jobs:[j]},{jobs:[j]}]).promise,n=normalizeJobs(r.jobs,site)[0];a.equal(n.date,null);a.equal(n.employment,'full-time');});
test('list JD CLI flag succeeds only after both scans; failures preserve old output',async t=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'ande-listjd-'));t.after(()=>fs.rmSync(d,{recursive:true,force:true}));const out=path.join(d,'raw.json'),args=['moonshot','148507','campus','de7c21ed8d6f50fe',out,'--list-jd'];fs.writeFileSync(out,'OLD');const f=fixture([{jobs:[job()]},{jobs:[job('a',{jobDescription:'changed'})]}]);await a.rejects(moka.run(args,{...f,sleep:async()=>{}}));a.equal(fs.readFileSync(out,'utf8'),'OLD');const ok=fixture([{jobs:[job()]},{jobs:[job()]}]);a.equal((await moka.run(args,{...ok,sleep:async()=>{}})).total,1);});
test('portal eligibility is pinned by real source identity/mode/origin, not a copied boolean',()=>{a.equal(moka.verifiedSource(site),true);for(const fields of [{key:'new'},{company:'冒充公司'},{siteId:9},{site:'social'},{url:site.url+'/'},{apiOrigin:'https://example.test'},{listJD:false},{fetchDetails:true},{adapter:'other'},{body:{}},{matchKeyword:'AI'}]){a.equal(moka.verifiedSource({...site,...fields}),false);a.throws(()=>normalizeJobs([],{...site,...fields}));}});
test('proven native fields, not unverified aliases or injected canonical claims, supply all public facts',()=>{const n=normalizeJobs([{...job(),listJDVerified:true,name:'冒充标题',category:'猜测职能',employment:'full-time',channels:['social'],talentPlan:true,dateKind:'updated',url:'https://example.test'}],site)[0];a.equal(n.title,'其他职业');a.equal(n.category,'市场');a.equal(n.employment,'internship');a.deepEqual(n.channels,['campus']);a.equal(n.talentPlan,null);a.equal(n.dateKind,'published');a.equal(n.url,site.url+'#/job/a');});
test('unknown Moka full-list source/origin rejects before any network call',async()=>{for(const fields of [{siteId:9},{apiOrigin:'https://example.test'},{apiOrigin:'https://jobs.hypergryph.com'},{fetchDetails:true}]){let calls=0;await a.rejects(moka.fetchAll({...site,...fields},{fetchImpl:async()=>{calls++;}}));a.equal(calls,0);}});
test('DeepSeek namespace attribution requires the separately verified official department, without adding a department filter',()=>{const s={...site,key:'deepseek',company:'DeepSeek',orgId:'high-flyer',siteId:140576,site:'social',url:'https://app.mokahr.com/social-recruitment/high-flyer/140576'};for(const fields of [{deptId:60243},{deptId:undefined},{orgId:'foreign'}])a.throws(()=>normalizeJobs([{...job(),orgId:'high-flyer',deptId:2028422,listJDVerified:true,...fields}],s));const n=normalizeJobs([{...job(),orgId:'high-flyer',deptId:2028422,listJDVerified:true,publishedAt:null,commitment:null}],s)[0];a.equal(n.date,null);a.equal(n.employment,null);a.deepEqual(n.channels,['social']);});
test('removing optional mode fields cannot unpin a previously verified target key, including an empty snapshot',()=>{const s={...site,fetchDetails:true,siteId:148508};for(const k of ['adapter','listJD','apiOrigin'])delete s[k];a.equal(moka.requiresVerification(s),true);a.equal(moka.verifiedSource(s),false);a.equal(require('../crawler/crawl').adapterCommand(s,'/tmp/unused'),null);a.throws(()=>normalizeJobs([],s));});
test('native metadata shape drift never becomes a factual type/category/location just because both scans match',async()=>{for(const fields of [{commitment:{name:'实习'}},{zhineng:['算法']},{locations:'猜测城市'}])await a.rejects(run([{jobs:[job('a',fields)]},{jobs:[job('a',fields)]}]).promise);});
test('invalid business status in an AES outer envelope is not washed away by a successful decrypted body',async()=>{const crypto=require('node:crypto'),key='1234567890123456',c=crypto.createCipheriv('aes-128-cbc',Buffer.from(key),Buffer.from(site.aesIv)),data=Buffer.concat([c.update(JSON.stringify({code:0,success:true,data:{jobStats:{orgId:site.orgId,total:0},jobs:[]}})),c.final()]).toString('base64');for(const field of ['success','Success'])for(const value of ['false',null,0])await a.rejects(moka.fetchAll(site,{fetchImpl:async()=>({status:200,text:async()=>JSON.stringify({data,necromancer:key,[field]:value})}),sleep:async()=>{}}));});
test('decoded inner Capital Success must not contradict the explicit lowercase success contract',async()=>{const crypto=require('node:crypto'),key='1234567890123456';const fetchFor=Success=>async()=>{const cipher=crypto.createCipheriv('aes-128-cbc',Buffer.from(key),Buffer.from(site.aesIv)),inner={code:0,success:true,Success,data:{jobStats:{orgId:'moonshot',total:0},jobs:[]}},data=Buffer.concat([cipher.update(JSON.stringify(inner)),cipher.final()]).toString('base64');return {status:200,text:async()=>JSON.stringify({data,necromancer:key})};};for(const Success of ['false',null,0,false])await a.rejects(moka.fetchAll(site,{fetchImpl:fetchFor(Success),sleep:async()=>{}}));a.equal((await moka.fetchAll(site,{fetchImpl:fetchFor(true),sleep:async()=>{}})).total,0);});
test('registered eagle social uses the independently proven custom origin/list JD strategy and official link',async()=>{const s=require('../crawler/sites.json').sites.find(s=>s.key==='hypergryph_social');a.equal(moka.verifiedSource(s),true);let calls=0;const r=await moka.fetchAll(s,{sleep:async()=>{},fetchImpl:async(url,opt)=>{a.ok(url.startsWith('https://jobs.hypergryph.com/'));a.ok(url.endsWith('/jobs/v2'));a.equal(JSON.parse(opt.body).siteId,'26325');calls++;return {status:200,text:async()=>JSON.stringify({code:0,success:true,data:{jobStats:{orgId:'hypergryph',total:1},jobs:[job('social',{orgId:'hypergryph'})]}})};}});a.equal(calls,2);const n=normalizeJobs(r.jobs,s)[0];a.equal(n.url,'https://jobs.hypergryph.com/apply/hypergryph/26325/#/job/social');a.deepEqual(n.channels,['social']);a.equal(n.jdComplete,true);});
test('native request scope is the observed unfiltered browser protocol, and rejects explicit failure even for empty jobs',async()=>{const {f,promise}=run([{jobs:[]},{jobs:[]}]);await promise;a.deepEqual(f.requests[0].body,{orgId:'moonshot',siteId:'148507',limit:30,offset:0,needStat:true,jobIdTopList:[],customFields:{},site:'campus',locale:'zh-CN'});a.equal(f.requests[0].headers['User-Agent'],undefined);for(const response of [{code:0,success:true,data:{jobStats:{orgId:'moonshot'},total:0,jobs:[]}},{code:0,data:{jobStats:{orgId:'moonshot',total:0},jobs:[]}},{code:0,success:true,data:{jobStats:{orgId:'foreign',total:0},jobs:[]}},{code:0,success:true,data:{jobStats:{orgId:'moonshot',total:0},list:[]}}])await a.rejects(moka.fetchAll(site,{fetchImpl:async()=>({status:200,text:async()=>JSON.stringify(response)})}));});
